name: CI of mc_naoqi

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 23 * * 0,1,4'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        build-type: [Debug, RelWithDebInfo]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup ROS dependencies (bionic)
      if: matrix.os == 'ubuntu-18.04'
      run: |
        set -e
        set -x
        pushd .
        export ROS_DISTRO="melodic"
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        sudo apt-get update -qq
        sudo apt-get install -qq ros-${ROS_DISTRO}-ros-base ros-${ROS_DISTRO}-naoqi-libqi ros-${ROS_DISTRO}-naoqi-libqicore
        . /opt/ros/${ROS_DISTRO}/setup.bash
        popd
    - name: Install libqi (noetic)
      if: matrix.os == 'ubuntu-20.04'
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: libgmock-dev libboost-all-dev
          pip: qibuild
        github: |
          - path: arntanguy/libqi
            ref: topic/boost-1.70
            options: -DQI_WITH_TESTS=OFF
    - name: Install mc_rtc
      run: |
        set -x
        set -e
        curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash
        sudo apt-get install -qq libmc-rtc-dev
    - name: Install dependencies (common)
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: libboost-all-dev
        github: |
          - path: jrl-umi3218/pepper_description
          - path: jrl-umi3218/mc_pepper
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}